In [1]:
5+10

15

# Downstream Meta Checkpoint Sweep

Evaluate the three downstream meta verifier checkpoints under the same attack suite used by `[3.a] attack_eval_our_improved_meta.ipynb`.

In [2]:
from types import SimpleNamespace
from pathlib import Path
import time

import pandas as pd
import torch
from torch.utils.data import DataLoader

from eval_downstream_meta_checkpoints import (
    build_validation_dataset,
    evaluate_checkpoint,
    load_pipe,
    set_seed,
)
from watermark import get_watermarking_mask, get_watermarking_pattern

## Config

In [3]:
args = SimpleNamespace(
    data_dir="./verifier_dataset_stablediff_octoweb",
    output_dir="./eval_results/downstream_meta_checkpoint_sweep",
    checkpoints=[
        "verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch116.pth",
        "verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch110.pth",
        "verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_final.pth",
    ],
    model_id="Manojb/stable-diffusion-2-1-base",
    batch_size=8,
    num_workers=0,
    testing_times=5,
    validation_split=0.15,
    seed=42,
    image_size=512,
    num_inference_steps=50,
    guidance_scale=7.5,
    w_mask_shape="circle",
    w_channel=0,
    w_radius=10,
    w_strength=0.99,
    w_pattern="octoweb",
    cpu=False,
)

device = "cpu" if args.cpu else ("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
print("Checkpoints:")
for ckpt in args.checkpoints:
    print(" -", ckpt)

Device: cuda
Checkpoints:
 - verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch116.pth
 - verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch110.pth
 - verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_final.pth

## Setup Pipeline And Validation Dataset

In [4]:
set_seed(args.seed)

missing = [path for path in args.checkpoints if not Path(path).exists()]
if missing:
    raise FileNotFoundError(f"Missing checkpoint(s): {missing}")

Path(args.output_dir).mkdir(parents=True, exist_ok=True)

pipe, text_embeddings = load_pipe(args, device)

watermarking_mask = get_watermarking_mask(
    pipe.get_random_latents(),
    w_mask_shape=args.w_mask_shape,
    w_channel=args.w_channel,
    w_radius=args.w_radius,
    device=device,
)

gt_patch = get_watermarking_pattern(
    pipe,
    w_seed=args.seed,
    w_pattern=args.w_pattern,
    w_radius=args.w_radius,
    device=device,
    strength=args.w_strength,
    shape=None,
)

dataset = build_validation_dataset(
    args, pipe, text_embeddings, watermarking_mask, gt_patch, device
)

loader = DataLoader(
    dataset,
    batch_size=args.batch_size,
    shuffle=False,
    num_workers=args.num_workers,
)

print("Ready. Validation dataset size:", len(dataset))

Keyword arguments {'verbose': False} are not expected by InversableStableDiffusionPipeline and will be ignored.

Loading pipeline components...:   0%|          | 0/6 [00:00<?, ?it/s]

`torch_dtype` is deprecated! Use `dtype` instead!

Validation samples: 150 / 1000
First validation labels: [1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0]
Ready. Validation dataset size: 150

d:\GitHub\watermarking\inverse_stable_diffusion.py:87: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet2DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet2DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.unet.in_channels
d:\GitHub\watermarking\watermark.py:471: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\EmptyTensor.cpp:58.)
  return gt_patch.to(dtype=torch.complex32)

## Run Evaluation

In [5]:
all_dfs = []
total_start = time.time()

for checkpoint_path in args.checkpoints:
    df = evaluate_checkpoint(checkpoint_path, args, pipe, dataset, loader, device)
    all_dfs.append(df)

combined = pd.concat(all_dfs, ignore_index=True)
combined_csv = Path(args.output_dir) / "combined_attack_eval_summary.csv"
combined.to_csv(combined_csv, index=False)

print("Combined summary:", combined_csv)
print(f"Total elapsed minutes: {(time.time() - total_start) / 60:.2f}")
combined

c:\Users\chihc\miniconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\chihc\miniconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)

================================================================================
Evaluating checkpoint: verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch116.pth
Output dir: eval_results\downstream_meta_checkpoint_sweep\epoch116
================================================================================
Using PNSRL1 wrapper for the model.
Loading checkpoint: verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch116.pth
Warning: couldn't fully load optimizer state: 'NoneType' object has no attribute 'load_state_dict'
Restored model and optimizer. Resuming from epoch 117

clean | Testing runs:   0%|          | 0/5 [00:00<?, ?it/s]d:\GitHub\watermarking\ds.py:153: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Copy.cpp:309.)
  mse = (diff.float() ** 2).mean().clamp_min(eps)
clean | Testing runs: 100%|██████████| 5/5 [24:37<00:00, 295.47s/it]

    epoch116 | clean          our_acc=0.9800 our_auc=0.9995 l1_acc=0.9867 psnr_acc=0.9800

jpeg_strong | Testing runs: 100%|██████████| 5/5 [24:58<00:00, 299.80s/it]

    epoch116 | jpeg_strong    our_acc=0.9347 our_auc=0.9867 l1_acc=0.6440 psnr_acc=0.6093

msg_app_combo | Testing runs: 100%|██████████| 5/5 [14:37<00:00, 175.56s/it]

    epoch116 | msg_app_combo  our_acc=0.9173 our_auc=0.9558 l1_acc=0.4800 psnr_acc=0.4760

down_up | Testing runs: 100%|██████████| 5/5 [14:36<00:00, 175.27s/it]

    epoch116 | down_up        our_acc=0.9533 our_auc=0.9939 l1_acc=0.7333 psnr_acc=0.5733

blur | Testing runs: 100%|██████████| 5/5 [14:41<00:00, 176.31s/it]

    epoch116 | blur           our_acc=0.9040 our_auc=0.9678 l1_acc=0.5000 psnr_acc=0.4787

random_crop | Testing runs: 100%|██████████| 5/5 [14:37<00:00, 175.43s/it]

    epoch116 | random_crop    our_acc=0.9027 our_auc=0.9691 l1_acc=0.6240 psnr_acc=0.5600

occlusion | Testing runs: 100%|██████████| 5/5 [14:39<00:00, 175.99s/it]

    epoch116 | occlusion      our_acc=0.9800 our_auc=0.9993 l1_acc=0.9733 psnr_acc=0.9467

geom_warp | Testing runs: 100%|██████████| 5/5 [14:51<00:00, 178.33s/it]

    epoch116 | geom_warp      our_acc=0.8893 our_auc=0.9626 l1_acc=0.5787 psnr_acc=0.5373

train_aug_mix | Testing runs: 100%|██████████| 5/5 [15:23<00:00, 184.62s/it]
c:\Users\chihc\miniconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\chihc\miniconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)

    epoch116 | train_aug_mix  our_acc=0.8027 our_auc=0.8830 l1_acc=0.5293 psnr_acc=0.5187
Saved checkpoint summary: eval_results\downstream_meta_checkpoint_sweep\epoch116\attack_eval_summary.csv

================================================================================
Evaluating checkpoint: verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch110.pth
Output dir: eval_results\downstream_meta_checkpoint_sweep\epoch110
================================================================================
Using PNSRL1 wrapper for the model.
Loading checkpoint: verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_epoch110.pth
Warning: couldn't fully load optimizer state: 'NoneType' object has no attribute 'load_state_dict'
Restored model and optimizer. Resuming from epoch 111

clean | Testing runs: 100%|██████████| 5/5 [19:46<00:00, 237.24s/it]

    epoch110 | clean          our_acc=0.9800 our_auc=0.9995 l1_acc=0.9867 psnr_acc=0.9800

jpeg_strong | Testing runs: 100%|██████████| 5/5 [16:09<00:00, 193.83s/it]

    epoch110 | jpeg_strong    our_acc=0.9413 our_auc=0.9887 l1_acc=0.6267 psnr_acc=0.6000

msg_app_combo | Testing runs: 100%|██████████| 5/5 [15:58<00:00, 191.63s/it]

    epoch110 | msg_app_combo  our_acc=0.9160 our_auc=0.9581 l1_acc=0.4800 psnr_acc=0.4733

down_up | Testing runs: 100%|██████████| 5/5 [15:49<00:00, 190.00s/it]

    epoch110 | down_up        our_acc=0.9467 our_auc=0.9945 l1_acc=0.7333 psnr_acc=0.5733

blur | Testing runs: 100%|██████████| 5/5 [15:25<00:00, 185.17s/it]

    epoch110 | blur           our_acc=0.8707 our_auc=0.9718 l1_acc=0.5053 psnr_acc=0.4773

random_crop | Testing runs: 100%|██████████| 5/5 [17:28<00:00, 209.67s/it]

    epoch110 | random_crop    our_acc=0.8933 our_auc=0.9619 l1_acc=0.6347 psnr_acc=0.5707

occlusion | Testing runs: 100%|██████████| 5/5 [26:05<00:00, 313.16s/it]

    epoch110 | occlusion      our_acc=0.9720 our_auc=0.9992 l1_acc=0.9667 psnr_acc=0.9427

geom_warp | Testing runs: 100%|██████████| 5/5 [26:00<00:00, 312.12s/it]

    epoch110 | geom_warp      our_acc=0.8813 our_auc=0.9559 l1_acc=0.5853 psnr_acc=0.5267

train_aug_mix | Testing runs: 100%|██████████| 5/5 [26:30<00:00, 318.02s/it]
c:\Users\chihc\miniconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\chihc\miniconda3\envs\pytorch\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)

    epoch110 | train_aug_mix  our_acc=0.7667 our_auc=0.8661 l1_acc=0.5320 psnr_acc=0.5187
Saved checkpoint summary: eval_results\downstream_meta_checkpoint_sweep\epoch110\attack_eval_summary.csv

================================================================================
Evaluating checkpoint: verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_final.pth
Output dir: eval_results\downstream_meta_checkpoint_sweep\final
================================================================================
Using PNSRL1 wrapper for the model.
Loading checkpoint: verifier_dataset_stablediff_octoweb_downstream_from_nvidia_meta_iter2000_300_final.pth
Warning: couldn't fully load optimizer state: 'NoneType' object has no attribute 'load_state_dict'
Restored model and optimizer. Resuming from epoch 301

clean | Testing runs: 100%|██████████| 5/5 [25:57<00:00, 311.60s/it]

       final | clean          our_acc=0.9467 our_auc=0.9993 l1_acc=0.9867 psnr_acc=0.9800

jpeg_strong | Testing runs: 100%|██████████| 5/5 [26:01<00:00, 312.34s/it]

       final | jpeg_strong    our_acc=0.9253 our_auc=0.9715 l1_acc=0.6373 psnr_acc=0.6040

msg_app_combo | Testing runs: 100%|██████████| 5/5 [25:58<00:00, 311.79s/it]

       final | msg_app_combo  our_acc=0.8973 our_auc=0.9404 l1_acc=0.4800 psnr_acc=0.4733

down_up | Testing runs: 100%|██████████| 5/5 [25:58<00:00, 311.68s/it]

       final | down_up        our_acc=0.9467 our_auc=0.9932 l1_acc=0.7333 psnr_acc=0.5733

blur | Testing runs: 100%|██████████| 5/5 [26:05<00:00, 313.08s/it]

       final | blur           our_acc=0.9347 our_auc=0.9732 l1_acc=0.5080 psnr_acc=0.4773

random_crop | Testing runs: 100%|██████████| 5/5 [25:56<00:00, 311.22s/it]

       final | random_crop    our_acc=0.8573 our_auc=0.9340 l1_acc=0.6213 psnr_acc=0.5600

occlusion | Testing runs: 100%|██████████| 5/5 [26:07<00:00, 313.55s/it]

       final | occlusion      our_acc=0.9587 our_auc=0.9969 l1_acc=0.9653 psnr_acc=0.9520

geom_warp | Testing runs: 100%|██████████| 5/5 [26:05<00:00, 313.08s/it]

       final | geom_warp      our_acc=0.8480 our_auc=0.9427 l1_acc=0.5680 psnr_acc=0.5307

train_aug_mix | Testing runs: 100%|██████████| 5/5 [26:20<00:00, 316.09s/it]

       final | train_aug_mix  our_acc=0.7480 our_auc=0.8389 l1_acc=0.5333 psnr_acc=0.5187
Saved checkpoint summary: eval_results\downstream_meta_checkpoint_sweep\final\attack_eval_summary.csv
Combined summary: eval_results\downstream_meta_checkpoint_sweep\combined_attack_eval_summary.csv
Total elapsed minutes: 566.85

,checkpoint_label,checkpoint,attack,our_acc,our_auc,best_our_thr,l1_acc,l1_auc,best_l1_thr,psnr_acc,psnr_auc,best_psnr_thr,clean_best_l1_thr,clean_best_psnr_thr,elapsed_sec
0,epoch116,verifier_dataset_stablediff_octoweb_downstream...,clean,0.980000,0.999465,0.996387,0.986667,0.998930,-45.78125,0.980000,0.995899,-17.788549,-45.78125,-17.788549,1477.354680
1,epoch116,verifier_dataset_stablediff_octoweb_downstream...,jpeg_strong,0.934667,0.986657,0.671122,0.644000,0.952252,-52.31250,0.609333,0.888707,-19.276882,-45.78125,-17.788549,1498.995419
2,epoch116,verifier_dataset_stablediff_octoweb_downstream...,msg_app_combo,0.917333,0.955800,0.470913,0.480000,0.870198,-56.78125,0.476000,0.728978,-20.411182,-45.78125,-17.788549,877.797375
3,epoch116,verifier_dataset_stablediff_octoweb_downstream...,down_up,0.953333,0.993938,0.686295,0.733333,0.985648,-53.75000,0.573333,0.943305,-19.649616,-45.78125,-17.788549,876.365754
4,epoch116,verifier_dataset_stablediff_octoweb_downstream...,blur,0.904000,0.967752,0.609815,0.500000,0.886311,-55.25000,0.478667,0.800121,-20.251005,-45.78125,-17.788549,881.555264
5,epoch116,verifier_dataset_stablediff_octoweb_downstream...,random_crop,0.902667,0.969107,0.511982,0.624000,0.975842,-52.21875,0.560000,0.947627,-19.271465,-45.78125,-17.788549,877.165881
6,epoch116,verifier_dataset_stablediff_octoweb_downstream...,occlusion,0.980000,0.999280,0.985542,0.973333,0.998224,-48.53125,0.946667,0.994138,-18.205666,-45.78125,-17.788549,879.964871
7,epoch116,verifier_dataset_stablediff_octoweb_downstream...,geom_warp,0.889333,0.962610,0.603340,0.578667,0.972430,-52.34375,0.537333,0.905438,-19.402058,-45.78125,-17.788549,891.645483
8,epoch116,verifier_dataset_stablediff_octoweb_downstream...,train_aug_mix,0.802667,0.883017,0.523349,0.529333,0.865819,-53.90625,0.518667,0.785053,-19.363953,-45.78125,-17.788549,923.096931
9,epoch110,verifier_dataset_stablediff_octoweb_downstream...,clean,0.980000,0.999465,0.997294,0.986667,0.998930,-45.78125,0.980000,0.995899,-17.788549,-45.78125,-17.788549,1186.181900
10,epoch110,verifier_dataset_stablediff_octoweb_downstream...,jpeg_strong,0.941333,0.988732,0.619783,0.626667,0.957515,-52.71875,0.600000,0.892808,-19.312042,-45.78125,-17.788549,969.157194
11,epoch110,verifier_dataset_stablediff_octoweb_downstream...,msg_app_combo,0.916000,0.958067,0.636030,0.480000,0.861269,-56.43750,0.473333,0.722475,-20.350822,-45.78125,-17.788549,958.158178
12,epoch110,verifier_dataset_stablediff_octoweb_downstream...,down_up,0.946667,0.994473,0.741280,0.733333,0.985648,-53.75000,0.573333,0.943305,-19.649616,-45.78125,-17.788549,949.999706
13,epoch110,verifier_dataset_stablediff_octoweb_downstream...,blur,0.870667,0.971788,0.727904,0.505333,0.888800,-54.15625,0.477333,0.805156,-19.905807,-45.78125,-17.788549,925.867385
14,epoch110,verifier_dataset_stablediff_octoweb_downstream...,random_crop,0.893333,0.961876,0.670450,0.634667,0.971956,-52.75000,0.570667,0.932302,-19.106668,-45.78125,-17.788549,1048.349374
15,epoch110,verifier_dataset_stablediff_octoweb_downstream...,occlusion,0.972000,0.999166,0.937774,0.966667,0.997903,-47.53125,0.942667,0.994865,-18.323780,-45.78125,-17.788549,1565.788260
16,epoch110,verifier_dataset_stablediff_octoweb_downstream...,geom_warp,0.881333,0.955935,0.662947,0.585333,0.966265,-52.06250,0.526667,0.917333,-19.186193,-45.78125,-17.788549,1560.583791
17,epoch110,verifier_dataset_stablediff_octoweb_downstream...,train_aug_mix,0.766667,0.866087,0.648957,0.532000,0.869210,-54.43750,0.518667,0.801790,-19.356581,-45.78125,-17.788549,1590.102932
18,final,verifier_dataset_stablediff_octoweb_downstream...,clean,0.946667,0.999287,0.999791,0.986667,0.998930,-45.78125,0.980000,0.995899,-17.788549,-45.78125,-17.788549,1557.996279
19,final,verifier_dataset_stablediff_octoweb_downstream...,jpeg_strong,0.925333,0.971531,0.820710,0.637333,0.953439,-53.56250,0.604000,0.895311,-19.427536,-45.78125,-17.788549,1561.697132
20,final,verifier_dataset_stablediff_octoweb_downstream...,msg_app_combo,0.897333,0.940403,0.310293,0.480000,0.860891,-56.43750,0.473333,0.707727,-20.203047,-45.78125,-17.788549,1558.936505
21,final,verifier_dataset_stablediff_octoweb_downstream...,down_up,0.946667,0.993225,0.930082,0.733333,0.985648,-53.75000,0.573333,0.943305,-19.649616,-45.78125,-17.788549,1558.399623
22,final,verifier_dataset_stablediff_octoweb_downstream...,blur,0.934667,0.973229,0.590404,0.508000,0.883819,-55.21875,0.477333,0.796948,-20.160500,-45.78125,-17.788549,1565.410547
23,final,verifier_dataset_stablediff_octoweb_downstream...,random_crop,0.857333,0.934027,0.937157,0.621333,0.977718,-52.50000,0.560000,0.933564,-19.270134,-45.78125,-17.788549,1556.084283
24,final,verifier_dataset_stablediff_octoweb_downstream...,occlusion,0.958667,0.996869,0.991685,0.965333,0.997451,-46.65625,0.952000,0.994459,-18.219961,-45.78125,-17.788549,1567.744672
25,final,verifier_dataset_stablediff_octoweb_downstream...,geom_warp,0.848000,0.942699,0.814393,0.568000,0.968814,-52.53125,0.530667,0.900731,-19.199566,-45.78125,-17.788549,1565.410108
26,final,verifier_dataset_stablediff_octoweb_downstream...,train_aug_mix,0.748000,0.838888,0.362405,0.533333,0.856520,-53.34375,0.518667,0.781180,-19.460854,-45.78125,-17.788549,1580.474162

## Accuracy Ranking

In [6]:
ranking = combined.sort_values(
    ["attack", "our_acc"], ascending=[True, False]
)[["attack", "checkpoint_label", "our_acc", "our_auc", "l1_acc", "psnr_acc"]]
ranking

           attack checkpoint_label   our_acc   our_auc    l1_acc  psnr_acc
22           blur            final  0.934667  0.973229  0.508000  0.477333
4            blur         epoch116  0.904000  0.967752  0.500000  0.478667
13           blur         epoch110  0.870667  0.971788  0.505333  0.477333
0           clean         epoch116  0.980000  0.999465  0.986667  0.980000
9           clean         epoch110  0.980000  0.999465  0.986667  0.980000
18          clean            final  0.946667  0.999287  0.986667  0.980000
3         down_up         epoch116  0.953333  0.993938  0.733333  0.573333
12        down_up         epoch110  0.946667  0.994473  0.733333  0.573333
21        down_up            final  0.946667  0.993225  0.733333  0.573333
7       geom_warp         epoch116  0.889333  0.962610  0.578667  0.537333
16      geom_warp         epoch110  0.881333  0.955935  0.585333  0.526667
25      geom_warp            final  0.848000  0.942699  0.568000  0.530667
10    jpeg_strong         epoch110  0.941333  0.988732  0.626667  0.600000
1     jpeg_strong         epoch116  0.934667  0.986657  0.644000  0.609333
19    jpeg_strong            final  0.925333  0.971531  0.637333  0.604000
2   msg_app_combo         epoch116  0.917333  0.955800  0.480000  0.476000
11  msg_app_combo         epoch110  0.916000  0.958067  0.480000  0.473333
20  msg_app_combo            final  0.897333  0.940403  0.480000  0.473333
6       occlusion         epoch116  0.980000  0.999280  0.973333  0.946667
15      occlusion         epoch110  0.972000  0.999166  0.966667  0.942667
24      occlusion            final  0.958667  0.996869  0.965333  0.952000
5     random_crop         epoch116  0.902667  0.969107  0.624000  0.560000
14    random_crop         epoch110  0.893333  0.961876  0.634667  0.570667
23    random_crop            final  0.857333  0.934027  0.621333  0.560000
8   train_aug_mix         epoch116  0.802667  0.883017  0.529333  0.518667
17  train_aug_mix         epoch110  0.766667  0.866087  0.532000  0.518667
26  train_aug_mix            final  0.748000  0.838888  0.533333  0.518667

## Mean Accuracy By Checkpoint

In [7]:
mean_scores = (
    combined.groupby("checkpoint_label", as_index=False)
    .agg(mean_our_acc=("our_acc", "mean"), mean_our_auc=("our_auc", "mean"))
    .sort_values("mean_our_acc", ascending=False)
)
mean_scores

  checkpoint_label  mean_our_acc  mean_our_auc
1         epoch116      0.918222      0.968625
0         epoch110      0.907556      0.966177
2            final      0.895852      0.954462